# Generated by Django 3.1 on 2020-08-26 07:07

import apps.core.fields
import apps.users.storages
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200807_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. From 6 to 30 characters. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(6)], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_myself',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=apps.core.fields.BaseImageField(blank=True, null=True, storage=apps.users.storages.UserImageStorage(), upload_to=apps.users.storages.user_image_path, verbose_name='avatar'),
        ),
    ]
