# Generated by Django 3.1 on 2020-10-31 04:03

import apps.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200928_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. From 6 to 30 characters. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[apps.users.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(30)], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True, verbose_name='VK ID'),
        ),
    ]
